#include "overrides.h"

static const struct core_override_option gambatte_core_option_overrides[] = {
	{
		.key = "gambatte_gb_colorization",
		.default_value = "internal",
		.info = "'Auto' selects the 'best' palette. 'Internal' uses 'Internal Palette' option. 'Custom' loads user palette from system directory.",
	},
	{
		.key = "gambatte_gb_internal_palette",
		.default_value = "TWB64 - Pack 1",
		.info = "Selects palette used when 'GB Colorization' is set to 'Internal.'",
		.options = {
			[50] = { "Special 4 (TI-83 Legacy)", "Special 4" },
			[51] = { "TWB64 - Pack 1", "TWB64 (1)" },
			[52] = { "TWB64 - Pack 2", "TWB64 (2)" },
			[53] = { "PixelShift - Pack 1", "PixelShift" },
		}
	},
	{
		.key = "gambatte_gb_palette_twb64_1",
		.desc = " > TWB64 (1)",
		.default_value = "TWB64 038 - Pokemon mini Ver.",
		.info = "Selects internal palette used when 'Internal Palette' is set to 'TWB64 (1)'.",
		.options = {
			{ "TWB64 001 - Aqours Blue",               "Aqours Blue 001",                },
			{ "TWB64 002 - Anime Expo Ver.",           "Anime Expo Ver. 002",            },
			{ "TWB64 003 - SpongeBob Yellow",          "SpongeBob Yellow 003",           },
			{ "TWB64 004 - Patrick Star Pink",         "Patrick Star Pink 004",          },
			{ "TWB64 005 - Neon Red",                  "Neon Red 005",                   },
			{ "TWB64 006 - Neon Blue",                 "Neon Blue 006",                  },
			{ "TWB64 007 - Neon Yellow",               "Neon Yellow 007",                },
			{ "TWB64 008 - Neon Green",                "Neon Green 008",                 },
			{ "TWB64 009 - Neon Pink",                 "Neon Pink 009",                  },
			{ "TWB64 010 - Mario Red",                 "Mario Red 010",                  },
			{ "TWB64 011 - Nick Orange",               "Nick Orange 011",                },
			{ "TWB64 012 - Virtual Boy Ver.",          "Virtual Boy Ver. 012",           },
			{ "TWB64 013 - Golden Wild",               "Golden Wild 013",                },
			{ "TWB64 014 - Builder Yellow",            "Builder Yellow 014",             },
			{ "TWB64 015 - Classic Blurple",           "Classic Blurple 015",            },
			{ "TWB64 016 - 765 Production Ver.",       "765 Production Ver. 016",        },
			{ "TWB64 017 - Superball Ivory",           "Superball Ivory 017",            },
			{ "TWB64 018 - Crunchyroll Orange",        "Crunchyroll Orange 018",         },
			{ "TWB64 019 - Muse Pink",                 "Muse Pink 019",                  },
			{ "TWB64 020 - Nijigasaki Yellow",         "Nijigasaki Yellow 020",          },
			{ "TWB64 021 - Gamate Ver.",               "Gamate Ver. 021",                },
			{ "TWB64 022 - Greenscale Ver.",           "Greenscale Ver. 022",            },
			{ "TWB64 023 - Odyssey Gold",              "Odyssey Gold 023",               },
			{ "TWB64 024 - Super Saiyan God",          "Super Saiyan God 024",           },
			{ "TWB64 025 - Super Saiyan Blue",         "Super Saiyan Blue 025",          },
			{ "TWB64 026 - Bizarre Pink",              "Bizarre Pink 026",               },
			{ "TWB64 027 - Nintendo Switch Lite Ver.", "Nintendo Switch Lite Ver. 027",  },
			{ "TWB64 028 - Game.com Ver.",             "Game.com Ver. 028",              },
			{ "TWB64 029 - Sanrio Pink",               "Sanrio Pink 029",                },
			{ "TWB64 030 - BANDAI NAMCO Ver.",         "BANDAI NAMCO Ver. 030",          },
			{ "TWB64 031 - Cosmo Green",               "Cosmo Green 031",                },
			{ "TWB64 032 - Wanda Pink",                "Wanda Pink 032",                 },
			{ "TWB64 033 - Link's Awakening DX Ver.",  "Link's Awakening DX Ver. 033",   },
			{ "TWB64 034 - Travel Wood",               "Travel Wood 034",                },
			{ "TWB64 035 - Pokemon Ver.",              "Pokemon Ver. 035",               },
			{ "TWB64 036 - Game Grump Orange",         "Game Grump Orange 036",          },
			{ "TWB64 037 - Scooby-Doo Mystery Ver.",   "Scooby-Doo Mystery Ver. 037",    },
			{ "TWB64 038 - Pokemon mini Ver.",         "Pokemon mini Ver. 038",          },
			{ "TWB64 039 - Supervision Ver.",          "Supervision Ver. 039",           },
			{ "TWB64 040 - DMG Ver.",                  "DMG Ver. 040",                   },
			{ "TWB64 041 - Pocket Ver.",               "Pocket Ver. 041",                },
			{ "TWB64 042 - Light Ver.",                "Light Ver. 042",                 },
			{ "TWB64 043 - Miraitowa Blue",            "Miraitowa Blue 043",             },
			{ "TWB64 044 - Someity Pink",              "Someity Pink 044",               },
			{ "TWB64 045 - Pikachu Yellow",            "Pikachu Yellow 045",             },
			{ "TWB64 046 - Eevee Brown",               "Eevee Brown 046",                },
			{ "TWB64 047 - Microvision Ver.",          "Microvision Ver. 047",           },
			{ "TWB64 048 - TI-83 Ver.",                "TI-83 Ver. 048",                 },
			{ "TWB64 049 - Aegis Cherry",              "Aegis Cherry 049",               },
			{ "TWB64 050 - Labo Fawn",                 "Labo Fawn 050",                  },
			{ "TWB64 051 - MILLION LIVE GOLD!",        "MILLION LIVE GOLD! 051",         },
			{ "TWB64 052 - Tokyo Midtown Ver.",        "Tokyo Midtown Ver. 052",         },
			{ "TWB64 053 - VMU Ver.",                  "VMU Ver. 053",                   },
			{ "TWB64 054 - Game Master Ver.",          "Game Master Ver. 054",           },
			{ "TWB64 055 - Android Green",             "Android Green 055",              },
			{ "TWB64 056 - Ticketmaster Azure",        "Ticketmaster Azure 056",         },
			{ "TWB64 057 - Google Red",                "Google Red 057",                 },
			{ "TWB64 058 - Google Blue",               "Google Blue 058",                },
			{ "TWB64 059 - Google Yellow",             "Google Yellow 059",              },
			{ "TWB64 060 - Google Green",              "Google Green 060",               },
			{ "TWB64 061 - WonderSwan Ver.",           "WonderSwan Ver. 061",            },
			{ "TWB64 062 - Neo Geo Pocket Ver.",       "Neo Geo Pocket Ver. 062",        },
			{ "TWB64 063 - Dew Green",                 "Dew Green 063",                  },
			{ "TWB64 064 - Coca-Cola Red",             "Coca-Cola Red 064",              },
			{ "TWB64 065 - GameKing Ver.",             "GameKing Ver. 065",              },
			{ "TWB64 066 - Do The Dew Ver.",           "Do The Dew Ver. 066",            },
			{ "TWB64 067 - Digivice Ver.",             "Digivice Ver. 067",              },
			{ "TWB64 068 - Bikini Bottom Ver.",        "Bikini Bottom Ver. 068",         },
			{ "TWB64 069 - Blossom Pink",              "Blossom Pink 069",               },
			{ "TWB64 070 - Bubbles Blue",              "Bubbles Blue 070",               },
			{ "TWB64 071 - Buttercup Green",           "Buttercup Green 071",            },
			{ "TWB64 072 - NASCAR Ver.",               "NASCAR Ver. 072",                },
			{ "TWB64 073 - Lemon-Lime Green",          "Lemon-Lime Green 073",           },
			{ "TWB64 074 - Mega Man V Ver.",           "Mega Man V Ver. 074",            },
			{ "TWB64 075 - Tamagotchi Ver.",           "Tamagotchi Ver. 075",            },
			{ "TWB64 076 - Phantom Red",               "Phantom Red 076",                },
			{ "TWB64 077 - Halloween Ver.",            "Halloween Ver. 077",             },
			{ "TWB64 078 - Christmas Ver.",            "Christmas Ver. 078",             },
			{ "TWB64 079 - Cardcaptor Pink",           "Cardcaptor Pink 079",            },
			{ "TWB64 080 - Pretty Guardian Gold",      "Pretty Guardian Gold 080",       },
			{ "TWB64 081 - Camouflage Ver.",           "Camouflage Ver. 081",            },
			{ "TWB64 082 - Legendary Super Saiyan",    "Legendary Super Saiyan 082",     },
			{ "TWB64 083 - Super Saiyan Rose",         "Super Saiyan Rose 083",          },
			{ "TWB64 084 - Super Saiyan",              "Super Saiyan 084",               },
			{ "TWB64 085 - Perfected Ultra Instinct",  "Perfected Ultra Instinct 085",   },
			{ "TWB64 086 - Saint Snow Red",            "Saint Snow Red 086",             },
			{ "TWB64 087 - Yellow Banana",             "Yellow Banana 087",              },
			{ "TWB64 088 - Green Banana",              "Green Banana 088",               },
			{ "TWB64 089 - Super Saiyan 3",            "Super Saiyan 3 089",             },
			{ "TWB64 090 - Super Saiyan Blue Evolved", "Super Saiyan Blue Evolved 090",  },
			{ "TWB64 091 - Pocket Tales Ver.",         "Pocket Tales Ver. 091",          },
			{ "TWB64 092 - Investigation Yellow",      "Investigation Yellow 092",       },
			{ "TWB64 093 - S.E.E.S. Blue",             "S.E.E.S. Blue 093",              },
			{ "TWB64 094 - Game Awards Cyan",          "Game Awards Cyan 094",           },
			{ "TWB64 095 - Hokage Orange",             "Hokage Orange 095",              },
			{ "TWB64 096 - Straw Hat Red",             "Straw Hat Red 096",              },
			{ "TWB64 097 - Sword Art Cyan",            "Sword Art Cyan 097",             },
			{ "TWB64 098 - Deku Alpha Emerald",        "Deku Alpha Emerald 098",         },
			{ "TWB64 099 - Blue Stripes Ver.",         "Blue Stripes Ver. 099",          },
			{ "TWB64 100 - Stone Orange",              "Stone Orange 100",               },
			{ NULL, NULL },
		}
	},
	{
		.key = "gambatte_gb_palette_twb64_2",
		.desc = " > TWB64 (2)",
		.info = "Selects internal palette used when 'Internal Palette' is set to 'TWB64 (2)'.",
		.options = {
         	{ "TWB64 101 - 765PRO Pink",               "765PRO Pink 101",                },
			{ "TWB64 102 - CINDERELLA Blue",           "CINDERELLA Blue 102",            },
			{ "TWB64 103 - MILLION Yellow!",           "MILLION Yellow! 103",            },
			{ "TWB64 104 - SideM Green",               "SideM Green 104",                },
			{ "TWB64 105 - SHINY Sky Blue",            "SHINY Sky Blue 105",             },
			{ "TWB64 106 - Angry Volcano Ver.",        "Angry Volcano Ver. 106",         },
			{ "TWB64 107 - Yo-kai Pink",               "Yo-kai Pink 107",                },
			{ "TWB64 108 - Yo-kai Green",              "Yo-kai Green 108",               },
			{ "TWB64 109 - Yo-kai Blue",               "Yo-kai Blue 109",                },
			{ "TWB64 110 - Yo-kai Purple",             "Yo-kai Purple 110",              },
			{ "TWB64 111 - Aquatic Iro",               "Aquatic Iro 111",                },
			{ "TWB64 112 - Tea Midori",                "Tea Midori 112",                 },
			{ "TWB64 113 - Sakura Pink",               "Sakura Pink 113",                },
			{ "TWB64 114 - Wisteria Murasaki",         "Wisteria Murasaki 114",          },
			{ "TWB64 115 - Oni Aka",                   "Oni Aka 115",                    },
			{ "TWB64 116 - Golden Kiiro",              "Golden Kiiro 116",               },
			{ "TWB64 117 - Silver Shiro",              "Silver Shiro 117",               },
			{ "TWB64 118 - Fruity Orange",             "Fruity Orange 118",              },
			{ "TWB64 119 - AKB48 Pink",                "AKB48 Pink 119",                 },
			{ "TWB64 120 - Miku Blue",                 "Miku Blue 120",                  },
			{ "TWB64 121 - Fairy Tail Red",            "Fairy Tail Red 121",             },
			{ "TWB64 122 - Survey Corps Brown",        "Survey Corps Brown 122",         },
			{ "TWB64 123 - Island Green",              "Island Green 123",               },
			{ "TWB64 124 - Mania Plus Green",          "Mania Plus Green 124",           },
			{ "TWB64 125 - Ninja Turtle Green",        "Ninja Turtle Green 125",         },
			{ "TWB64 126 - Slime Blue",                "Slime Blue 126",                 },
			{ "TWB64 127 - Lime Midori",               "Lime Midori 127",                },
			{ "TWB64 128 - Ghostly Aoi",               "Ghostly Aoi 128",                },
			{ "TWB64 129 - Retro Bogeda",              "Retro Bogeda 129",               },
			{ "TWB64 130 - Royal Blue",                "Royal Blue 130",                 },
			{ "TWB64 131 - Neon Purple",               "Neon Purple 131",                },
			{ "TWB64 132 - Neon Orange",               "Neon Orange 132",                },
			{ "TWB64 133 - Moonlight Vision",          "Moonlight Vision 133",           },
			{ "TWB64 134 - Tokyo Red",                 "Tokyo Red 134",                  },
			{ "TWB64 135 - Paris Gold",                "Paris Gold 135",                 },
			{ "TWB64 136 - Beijing Blue",              "Beijing Blue 136",               },
			{ "TWB64 137 - Pac-Man Yellow",            "Pac-Man Yellow 137",             },
			{ "TWB64 138 - Irish Green",               "Irish Green 138",                },
			{ "TWB64 139 - Kakarot Orange",            "Kakarot Orange 139",             },
			{ "TWB64 140 - Dragon Ball Orange",        "Dragon Ball Orange 140",         },
			{ "TWB64 141 - Christmas Gold",            "Christmas Gold 141",             },
			{ "TWB64 142 - Pepsi-Cola Blue",           "Pepsi-Cola Blue 142",            },
			{ "TWB64 143 - Bubblun Green",             "Bubblun Green 143",              },
			{ "TWB64 144 - Bobblun Blue",              "Bobblun Blue 144",               },
			{ "TWB64 145 - Baja Blast Storm",          "Baja Blast Storm 145",           },
			{ "TWB64 146 - Olympic Gold",              "Olympic Gold 146",               },
			{ "TWB64 147 - Value Orange",              "Value Orange 147",               },
			{ "TWB64 148 - Liella Purple!",            "Liella Purple! 148",             },
			{ "TWB64 149 - Olympic Silver",            "Olympic Silver 149",             },
			{ "TWB64 150 - Olympic Bronze",            "Olympic Bronze 150",             },
			{ "TWB64 151 - ANA Sky Blue",              "ANA Sky Blue 151",               },
			{ "TWB64 152 - Nijigasaki Orange",         "Nijigasaki Orange 152",          },
			{ "TWB64 153 - HoloBlue",                  "HoloBlue 153",                   },
			{ "TWB64 154 - Wrestling Red",             "Wrestling Red 154",              },
			{ "TWB64 155 - Yoshi Egg Green",           "Yoshi Egg Green 155",            },
			{ "TWB64 156 - Pokedex Red",               "Pokedex Red 156",                },
			{ "TWB64 157 - Disney Dream Blue",         "Disney Dream Blue 157",          },
			{ "TWB64 158 - Xbox Green",                "Xbox Green 158",                 },
			{ "TWB64 159 - Sonic Mega Blue",           "Sonic Mega Blue 159",            },
			{ "TWB64 160 - G4 Orange",                 "G4 Orange 160",                  },
			{ "TWB64 161 - Scarlett Green",            "Scarlett Green 161",             },
			{ "TWB64 162 - Glitchy Blue",              "Glitchy Blue 162",               },
			{ "TWB64 163 - Classic LCD",               "Classic LCD 163",                },
			{ "TWB64 164 - 3DS Virtual Console Ver.",  "3DS Virtual Console Ver. 164",   },
			{ "TWB64 165 - PocketStation Ver.",        "PocketStation Ver. 165",         },
			{ "TWB64 166 - Game and Gold",             "Game and Gold 166",              },
			{ "TWB64 167 - Smurfy Blue",               "Smurfy Blue 167",                },
			{ "TWB64 168 - Swampy Ogre Green",         "Swampy Ogre Green 168",          },
			{ "TWB64 169 - Sailor Spinach Green",      "Sailor Spinach Green 169",       },
			{ "TWB64 170 - Shenron Green",             "Shenron Green 170",              },
			{ "TWB64 171 - Berserk Blood",             "Berserk Blood 171",              },
			{ "TWB64 172 - Super Star Pink",           "Super Star Pink 172",            },
			{ "TWB64 173 - Gamebuino Classic Ver.",    "Gamebuino Classic Ver. 173",     },
			{ "TWB64 174 - Barbie Pink",               "Barbie Pink 174",                },
			{ "TWB64 175 - Star Command Green",        "Star Command Green 175",         },
			{ "TWB64 176 - Nokia 3310 Ver.",           "Nokia 3310 Ver. 176",            },
			{ "TWB64 177 - Clover Green",              "Clover Green 177",               },
			{ "TWB64 178 - Crash Orange",              "Crash Orange 178",               },
			{ "TWB64 179 - Famicom Disk Yellow",       "Famicom Disk Yellow 179",        },
			{ "TWB64 180 - Team Rocket Red",           "Team Rocket Red 180",            },
			{ "TWB64 181 - SEIKO Timer Yellow",        "SEIKO Timer Yellow 181",         },
			{ "TWB64 182 - PINK109",                   "PINK109 182",                    },
			{ "TWB64 183 - Doraemon Blue",             "Doraemon Blue 183",              },
			{ "TWB64 184 - Fury Blue",                 "Fury Blue 184",                  },
			{ "TWB64 185 - Rockstar Orange",           "Rockstar Orange 185",            },
			{ "TWB64 186 - Puyo Puyo Green",           "Puyo Puyo Green 186",            },
			{ "TWB64 187 - Susan G. Pink",             "Susan G. Pink 187",              },
			{ "TWB64 188 - Pizza Hut Red",             "Pizza Hut Red 188",              },
			{ "TWB64 189 - Plumbob Green",             "Plumbob Green 189",              },
			{ "TWB64 190 - Grand Ivory",               "Grand Ivory 190",                },
			{ "TWB64 191 - Demon's Gold",              "Demon's Gold 191",               },
			{ "TWB64 192 - SEGA Tokyo Blue",           "SEGA Tokyo Blue 192",            },
			{ "TWB64 193 - Champion Blue",             "Champion Blue 193",              },
			{ "TWB64 194 - DK Barrel Brown",           "DK Barrel Brown 194",            },
			{ "TWB64 195 - Evangelion Green",          "Evangelion Green 195",           },
			{ "TWB64 196 - Equestrian Purple",         "Equestrian Purple 196",          },
			{ "TWB64 197 - Autobot Red",               "Autobot Red 197",                },
			{ "TWB64 198 - Niconico Sea Green",        "Niconico Sea Green 198",         },
			{ "TWB64 199 - Duracell Copper",           "Duracell Copper 199",            },
			{ "TWB64 200 - TOKYO SKYTREE CLOUDY BLUE", "TOKYO SKYTREE CLOUDY BLUE 200",  },
			{ NULL, NULL },
		}
	},
	{
		.key = "gambatte_gb_palette_pixelshift_1",
		.desc = " > PixelShift",
		.info = "Selects internal palette used when 'Internal Palette' is set to 'PixelShift'.",
		.options = {
         	{ "PixelShift 01 - Arctic Green",               "Arctic Green 001",                },
			{ "PixelShift 02 - Arduboy",                    "Arduboy 002",                     },
			{ "PixelShift 03 - BGB 0.3 Emulator",           "BGB 0.3 Emulator 003",            },
			{ "PixelShift 04 - Camouflage",                 "Camouflage 004",                  },
			{ "PixelShift 05 - Chocolate Bar",              "Chocolate Bar 005",               },
			{ "PixelShift 06 - CMYK",                       "CMYK 006",                        },
			{ "PixelShift 07 - Cotton Candy",               "Cotton Candy 007",                },
			{ "PixelShift 08 - Easy Greens",                "Easy Greens 008",                 },
			{ "PixelShift 09 - Gamate",                     "Gamate 009",                      },
			{ "PixelShift 10 - Game Boy Light",             "Game Boy Light 010",              },
			{ "PixelShift 11 - Game Boy Pocket",            "Game Boy Pocket 011",             },
			{ "PixelShift 12 - Game Boy Pocket Alt",        "Game Boy Pocket Alt 012",         },
			{ "PixelShift 13 - Game Pocket Computer",       "Game Pocket Computer 013",        },
			{ "PixelShift 14 - Game & Watch Ball",          "Game & Watch Ball 014",           },
			{ "PixelShift 15 - GB Backlight Blue",          "GB Backlight Blue 015",           },
			{ "PixelShift 16 - GB Backlight Faded",         "GB Backlight Faded 016",          },
			{ "PixelShift 17 - GB Backlight Orange",        "GB Backlight Orange 017",         },
			{ "PixelShift 18 - GB Backlight White ",        "GB Backlight White  018",         },
			{ "PixelShift 19 - GB Backlight Yellow Dark",   "GB Backlight Yellow Dark 019",    },
			{ "PixelShift 20 - GB Bootleg",                 "GB Bootleg 020",                  },
			{ "PixelShift 21 - GB Hunter",                  "GB Hunter 021",                   },
			{ "PixelShift 22 - GB Kiosk",                   "GB Kiosk 022",                    },
			{ "PixelShift 23 - GB Kiosk 2",                 "GB Kiosk 2 023",                  },
			{ "PixelShift 24 - GB New",                     "GB New 024",                      },
			{ "PixelShift 25 - GB Nuked",                   "GB Nuked 025",                    },
			{ "PixelShift 26 - GB Old",                     "GB Old 026",                      },
			{ "PixelShift 27 - GBP Bivert",                 "GBP Bivert 027",                  },
			{ "PixelShift 28 - GB Washed Yellow Backlight", "GB Washed Yellow Backlight 028",  },
			{ "PixelShift 29 - Ghost",                      "Ghost 029",                       },
			{ "PixelShift 30 - Glow In The Dark",           "Glow In The Dark 030",            },
			{ "PixelShift 31 - Gold Bar",                   "Gold Bar 031",                    },
			{ "PixelShift 32 - Grapefruit",                 "Grapefruit 032",                  },
			{ "PixelShift 33 - Gray Green Mix",             "Gray Green Mix 033",              },
			{ "PixelShift 34 - Missingno",                  "Missingno 034",                   },
			{ "PixelShift 35 - MS-Dos",                     "MS-Dos 035",                      },
			{ "PixelShift 36 - Newspaper",                  "Newspaper 036",                   },
			{ "PixelShift 37 - Pip-Boy",                    "Pip-Boy 037",                     },
			{ "PixelShift 38 - Pocket Girl",                "Pocket Girl 038",                 },
			{ "PixelShift 39 - Silhouette",                 "Silhouette 039",                  },
			{ "PixelShift 40 - Sunburst",                   "Sunburst 040",                    },
			{ "PixelShift 41 - Technicolor",                "Technicolor 041",                 },
			{ "PixelShift 42 - Tron",                       "Tron 042",                        },
			{ "PixelShift 43 - Vaporwave",                  "Vaporwave 043",                   },
			{ "PixelShift 44 - Virtual Boy",                "Virtual Boy 044",                 },
			{ "PixelShift 45 - Wish",                       "Wish 045",                        },
			{ NULL, NULL },
		}
	},
	{
		.key = "gambatte_gbc_color_correction",
		.info = "Adjusts colors to match the display of real GBC hardware. 'GBC Only' only applies correction when playing GBC games or using a GBC palette.",
		.default_value = "disabled",
	},
	{
		.key = "gambatte_gbc_color_correction_mode",
		.desc = "CC Mode",
		.info = "'Accurate' produces output almost indistinguishable from a real GBC LCD panel. 'Fast' merely darkens colors and reduces saturation.",
		.default_value = "fast",
	},
	{
		.key = "gambatte_gbc_frontlight_position",
		.desc = "CC Frontlight",
		.info = "Simulates the GBC LCD panel when illuminated from different angles. This setting only applies when 'Color Correction Mode' is set to 'Accurate'."
	},
	{
		.key = "gambatte_dark_filter_level",
		.desc = "Dark Level",
		.info = "Enable luminosity-based brightness reduction. May be used to avoid glare/eye strain when playing games with white backgrounds."
	},
	{
		.key = "gambatte_gb_hwmode",
		.desc = "Hardware (restart)",
		.info = "Which type of hardware to emulate. 'Auto' is recommended. 'GBA' unlocks extra features in certain 'GBA enhanced' Game Boy Color games."
	},
	{
		.key = "gambatte_gb_bootloader",
		.desc = "Boot Logo (restart)",
		.default_value = "disabled",
	},
	{
		.key = "gambatte_mix_frames",
		.desc = "Blending",
		.info = "Simulates LCD ghosting effects. 'Simple' performs a 50:50 mix. 'Ghosting' mimics LCD response times with multiple buffered frames.",
		.options = {
			[2] = { "lcd_ghosting",         "Ghosting (Accurate)" },
			[3] = { "lcd_ghosting_fast",    "Ghosting (Fast)"     },
			[4] = { "lcd_ghosting_fastest", "Ghosting (Fastest)"  },
		}
	},
	{
		.key = "gambatte_up_down_allowed",
		.desc = "Opp. Directions",
		.info = "Enabling this will allow pressing both left and right (or up and down) directions at the same time."
	},
	{
		.key = "gambatte_rumble_level",
		.desc = "Rumble Level",
		.default_value = "2",
	},
	{
		.key = "gambatte_audio_resampler",
		.default_value = "sinc",
		.blocked = true
	},
	{
		.key = "gambatte_show_gb_link_settings",
		.blocked = true
	},
	{ NULL }
};

me_bind_action gambatte_ctrl_actions[] =
{
	{ "UP       ",  1 << RETRO_DEVICE_ID_JOYPAD_UP},
	{ "DOWN     ",  1 << RETRO_DEVICE_ID_JOYPAD_DOWN },
	{ "LEFT     ",  1 << RETRO_DEVICE_ID_JOYPAD_LEFT },
	{ "RIGHT    ",  1 << RETRO_DEVICE_ID_JOYPAD_RIGHT },
	{ "A BUTTON ",  1 << RETRO_DEVICE_ID_JOYPAD_A },
	{ "B BUTTON ",  1 << RETRO_DEVICE_ID_JOYPAD_B },
	{ "A TURBO  ",  1 << RETRO_DEVICE_ID_JOYPAD_X },
	{ "B TURBO  ",  1 << RETRO_DEVICE_ID_JOYPAD_Y },
	{ "START    ",  1 << RETRO_DEVICE_ID_JOYPAD_START },
	{ "SELECT   ",  1 << RETRO_DEVICE_ID_JOYPAD_SELECT },
	{ NULL,       0 }
};

#define gambatte_overrides {                                    \
	.core_name = "gambatte",                                \
	.actions = gambatte_ctrl_actions,                       \
	.action_size = array_size(gambatte_ctrl_actions),       \
	.options = gambatte_core_option_overrides               \
}
